[project]
name = "video-gen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.7.1",
    "elevenlabs>=1.3.0",
    "python-dotenv>=1.0.0",
]
